<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bansari Kathrotia">
<meta name="dcterms.date" content="2024-05-16">

<title>Bansari’s Website - Poisson Regression Examples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Bansari’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estimating-yogurt-preferences" id="toc-estimating-yogurt-preferences" class="nav-link active" data-scroll-target="#estimating-yogurt-preferences">1. Estimating Yogurt Preferences</a>
  <ul class="collapse">
  <li><a href="#likelihood-for-the-multi-nomial-logit-mnl-model" id="toc-likelihood-for-the-multi-nomial-logit-mnl-model" class="nav-link" data-scroll-target="#likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</a></li>
  <li><a href="#yogurt-dataset" id="toc-yogurt-dataset" class="nav-link" data-scroll-target="#yogurt-dataset">Yogurt Dataset</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation">Estimation</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#which-yogurt-is-most-preferred" id="toc-which-yogurt-is-most-preferred" class="nav-link" data-scroll-target="#which-yogurt-is-most-preferred">Which yogurt is most preferred?</a></li>
  <li><a href="#current-market-shares" id="toc-current-market-shares" class="nav-link" data-scroll-target="#current-market-shares">Current Market Shares:</a></li>
  <li><a href="#new-market-shares-after-a-0.10-price-increase-to-yogurt-1" id="toc-new-market-shares-after-a-0.10-price-increase-to-yogurt-1" class="nav-link" data-scroll-target="#new-market-shares-after-a-0.10-price-increase-to-yogurt-1">New Market Shares After a $0.10 Price Increase to Yogurt 1:</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis:</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion:</a></li>
  </ul></li>
  <li><a href="#estimating-minivan-preferences" id="toc-estimating-minivan-preferences" class="nav-link" data-scroll-target="#estimating-minivan-preferences">2. Estimating Minivan Preferences</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#market-share-interpretation" id="toc-market-share-interpretation" class="nav-link" data-scroll-target="#market-share-interpretation">Market Share Interpretation</a></li>
  <li><a href="#overall-insights" id="toc-overall-insights" class="nav-link" data-scroll-target="#overall-insights">Overall Insights</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bansari Kathrotia </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This assignment uses the MNL model to analyze (1) yogurt purchase data made by consumers at a retail location, and (2) conjoint data about consumer preferences for minivans.</p>
<section id="estimating-yogurt-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-yogurt-preferences">1. Estimating Yogurt Preferences</h2>
<section id="likelihood-for-the-multi-nomial-logit-mnl-model" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-for-the-multi-nomial-logit-mnl-model">Likelihood for the Multi-nomial Logit (MNL) Model</h3>
<p>Suppose we have <span class="math inline">\(i=1,\ldots,n\)</span> consumers who each select exactly one product <span class="math inline">\(j\)</span> from a set of <span class="math inline">\(J\)</span> products. The outcome variable is the identity of the product chosen <span class="math inline">\(y_i \in \{1, \ldots, J\}\)</span> or equivalently a vector of <span class="math inline">\(J-1\)</span> zeros and <span class="math inline">\(1\)</span> one, where the <span class="math inline">\(1\)</span> indicates the selected product. For example, if the third product was chosen out of 4 products, then either <span class="math inline">\(y=3\)</span> or <span class="math inline">\(y=(0,0,1,0)\)</span> depending on how we want to represent it. Suppose also that we have a vector of data on each product <span class="math inline">\(x_j\)</span> (eg, size, price, etc.).</p>
<p>We model the consumer’s decision as the selection of the product that provides the most utility, and we’ll specify the utility function as a linear function of the product characteristics:</p>
<p><span class="math display">\[ U_{ij} = x_j'\beta + \epsilon_{ij} \]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an i.i.d. extreme value error term.</p>
<p>The choice of the i.i.d. extreme value error term leads to a closed-form expression for the probability that consumer <span class="math inline">\(i\)</span> chooses product <span class="math inline">\(j\)</span>:</p>
<p><span class="math display">\[ \mathbb{P}_i(j) = \frac{e^{x_j'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>For example, if there are 4 products, the probability that consumer <span class="math inline">\(i\)</span> chooses product 3 is:</p>
<p><span class="math display">\[ \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{e^{x_1'\beta} + e^{x_2'\beta} + e^{x_3'\beta} + e^{x_4'\beta}} \]</span></p>
<p>A clever way to write the individual likelihood function for consumer <span class="math inline">\(i\)</span> is the product of the <span class="math inline">\(J\)</span> probabilities, each raised to the power of an indicator variable (<span class="math inline">\(\delta_{ij}\)</span>) that indicates the chosen product:</p>
<p><span class="math display">\[ L_i(\beta) = \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} = \mathbb{P}_i(1)^{\delta_{i1}} \times \ldots \times \mathbb{P}_i(J)^{\delta_{iJ}}\]</span></p>
<p>Notice that if the consumer selected product <span class="math inline">\(j=3\)</span>, then <span class="math inline">\(\delta_{i3}=1\)</span> while <span class="math inline">\(\delta_{i1}=\delta_{i2}=\delta_{i4}=0\)</span> and the likelihood is:</p>
<p><span class="math display">\[ L_i(\beta) = \mathbb{P}_i(1)^0 \times \mathbb{P}_i(2)^0 \times \mathbb{P}_i(3)^1 \times \mathbb{P}_i(4)^0 = \mathbb{P}_i(3) = \frac{e^{x_3'\beta}}{\sum_{k=1}^Je^{x_k'\beta}} \]</span></p>
<p>The joint likelihood (across all consumers) is the product of the <span class="math inline">\(n\)</span> individual likelihoods:</p>
<p><span class="math display">\[ L_n(\beta) = \prod_{i=1}^n L_i(\beta) = \prod_{i=1}^n \prod_{j=1}^J \mathbb{P}_i(j)^{\delta_{ij}} \]</span></p>
<p>And the joint log-likelihood function is:</p>
<p><span class="math display">\[ \ell_n(\beta) = \sum_{i=1}^n \sum_{j=1}^J \delta_{ij} \log(\mathbb{P}_i(j)) \]</span></p>
</section>
<section id="yogurt-dataset" class="level3">
<h3 class="anchored" data-anchor-id="yogurt-dataset">Yogurt Dataset</h3>
<p>We will use the <code>yogurt_data</code> dataset, which provides anonymized consumer identifiers (<code>id</code>), a vector indicating the chosen product (<code>y1</code>:<code>y4</code>), a vector indicating if any products were “featured” in the store as a form of advertising (<code>f1</code>:<code>f4</code>), and the products’ prices (<code>p1</code>:<code>p4</code>). For example, consumer 1 purchased yogurt 4 at a price of 0.079/oz and none of the yogurts were featured/advertised at the time of consumer 1’s purchase. Consumers 2 through 7 each bought yogurt 2, etc.</p>
<div id="5ba7747e" class="cell" data-message="true" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">y1</th>
<th data-quarto-table-cell-role="th">y2</th>
<th data-quarto-table-cell-role="th">y3</th>
<th data-quarto-table-cell-role="th">y4</th>
<th data-quarto-table-cell-role="th">f1</th>
<th data-quarto-table-cell-role="th">f2</th>
<th data-quarto-table-cell-role="th">f3</th>
<th data-quarto-table-cell-role="th">f4</th>
<th data-quarto-table-cell-role="th">p1</th>
<th data-quarto-table-cell-role="th">p2</th>
<th data-quarto-table-cell-role="th">p3</th>
<th data-quarto-table-cell-role="th">p4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.081</td>
<td>0.061</td>
<td>0.079</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.098</td>
<td>0.064</td>
<td>0.075</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.098</td>
<td>0.061</td>
<td>0.086</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.098</td>
<td>0.061</td>
<td>0.086</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.125</td>
<td>0.098</td>
<td>0.049</td>
<td>0.079</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2425</td>
<td>2426</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.122</td>
<td>0.086</td>
<td>0.061</td>
<td>0.086</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2426</td>
<td>2427</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.122</td>
<td>0.086</td>
<td>0.061</td>
<td>0.086</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2427</td>
<td>2428</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.122</td>
<td>0.086</td>
<td>0.061</td>
<td>0.086</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2428</td>
<td>2429</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.122</td>
<td>0.086</td>
<td>0.050</td>
<td>0.086</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2429</td>
<td>2430</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>0.086</td>
<td>0.043</td>
<td>0.079</td>
</tr>
</tbody>
</table>

<p>2430 rows × 13 columns</p>
</div>
</div>
</div>
</div>
<p>The dataset contains the following columns:</p>
<ul>
<li><code>id</code>: Unique identifier for each consumer.</li>
<li><code>y1</code> to <code>y4</code>: Binary indicators showing which of the four yogurts was chosen by the consumer. Only one of these columns will have a value of <code>1</code> per row, indicating the chosen product.</li>
<li><code>f1</code> to <code>f4</code>: Binary indicators showing whether each of the four yogurts was featured (advertised) in the store at the time of the purchase.</li>
<li><code>p1</code> to <code>p4</code>: Numeric values representing the price per ounce of each of the four yogurts.</li>
</ul>
<p>From the preview of the data:</p>
<ul>
<li>In the first row, consumer with <code>id</code> 1 purchased yogurt 4 (as indicated by <code>y4</code> = 1) at a price of 0.079 per ounce. None of the yogurts were featured.</li>
<li>Subsequent rows show similar data for other consumers, indicating their choices and the conditions (price and whether the product was featured) under each product.</li>
</ul>
<p>Let the vector of product features include brand dummy variables for yogurts 1-3 (we’ll omit a dummy for product 4 to avoid multi-collinearity), a dummy variable to indicate if a yogurt was featured, and a continuous variable for the yogurts’ prices:</p>
<p><span class="math display">\[ x_j' = [\mathbbm{1}(\text{Yogurt 1}), \mathbbm{1}(\text{Yogurt 2}), \mathbbm{1}(\text{Yogurt 3}), X_f, X_p] \]</span></p>
<p>The “hard part” of the MNL likelihood function is organizing the data, as we need to keep track of 3 dimensions (consumer <span class="math inline">\(i\)</span>, covariate <span class="math inline">\(k\)</span>, and product <span class="math inline">\(j\)</span>) instead of the typical 2 dimensions for cross-sectional regression models (consumer <span class="math inline">\(i\)</span> and covariate <span class="math inline">\(k\)</span>).</p>
<p>What we would like to do is reorganize the data from a “wide” shape with <span class="math inline">\(n\)</span> rows and multiple columns for each covariate, to a “long” shape with <span class="math inline">\(n \times J\)</span> rows and a single column for each covariate. As part of this re-organization, we’ll add binary variables to indicate the first 3 products; the variables for featured and price are included in the dataset and simply need to be “pivoted” or “melted” from wide to long.</p>
<p>Let’s reshape the dataset for analysis:</p>
<div id="a21bcb70" class="cell" data-message="true" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">choice</th>
<th data-quarto-table-cell-role="th">featured</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">product</th>
<th data-quarto-table-cell-role="th">brand1</th>
<th data-quarto-table-cell-role="th">brand2</th>
<th data-quarto-table-cell-role="th">brand3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0.108</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>0.125</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>The dataset has been reshaped into the long format using the dataset named “yogurt”. Here is the structure of the transformed data:</p>
<ul>
<li><code>id</code>: Consumer identifier.</li>
<li><code>choice</code>: Indicates whether the consumer chose this product (1 if chosen, 0 otherwise).</li>
<li><code>featured</code>: Indicates whether the product was featured (1 if featured, 0 otherwise).</li>
<li><code>price</code>: Price per ounce of the product.</li>
<li><code>product</code>: Product number (1 through 4).</li>
<li><code>brand1</code>, <code>brand2</code>, <code>brand3</code>: Dummy variables for the first three products, with the fourth product omitted to avoid multicollinearity.</li>
</ul>
</section>
<section id="estimation" class="level3">
<h3 class="anchored" data-anchor-id="estimation">Estimation</h3>
<ol type="1">
<li><strong>Utility Function</strong>: Calculates the utility for each product based on the beta coefficients and the features in the dataset.</li>
<li><strong>Probability Calculation</strong>: Determines the probabilities of choosing each product by a consumer, factoring in the utilities of all available products for normalization.</li>
<li><strong>Log-Likelihood</strong>: Computes the log of these probabilities where the product was actually chosen (where <code>choice == 1</code>) and sums these values to obtain the log-likelihood for the dataset given the model parameters.</li>
</ol>
<div id="9708f7e9" class="cell" data-message="true" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Log-Likelihood Value: -3570.660714305375</code></pre>
</div>
</div>
<p>Optimizin gthe model to find the MLEs for the 5 parameters (<span class="math inline">\(\beta_1, \beta_2, \beta_3, \beta_f, \beta_p\)</span>). (Hint: you should find 2 positive and 1 negative product intercepts, a small positive coefficient estimate for featured, and a large negative coefficient estimate for price.)</p>
<div id="c905a389" class="cell" data-message="true" data-execution_count="8">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimization to find the MLE of the beta coefficients</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize(negative_log_likelihood, initial_beta, args<span class="op">=</span>(long_data_final,), </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                  method<span class="op">=</span><span class="st">'L-BFGS-B'</span>, bounds<span class="op">=</span>bounds)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the optimization results</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Optimization Success:"</span>, result.success)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estimated beta coefficients:"</span>, result.x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization Success: True
Estimated beta coefficients: [  1.38775763   0.6435053   -3.08612024   0.48741136 -37.05807603]</code></pre>
</div>
</div>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>We learn…</p>
<p>From the three product intercepts from the estimated beta coefficients for Brands 1, 2, and 3, we can gauge consumer preferences among the yogurt options relative to the baseline (Brand 4, which does not have a specific intercept and is implied as zero in the model). Here’s how to interpret the intercepts:</p>
<ol type="1">
<li><p><strong>Beta for Brand 1 (<code>beta_1</code>)</strong>: 1.388</p>
<ul>
<li>This positive intercept suggests that, holding other factors constant (such as price and whether the product was featured), Brand 1 is preferred over Brand 4. The higher positive value indicates a strong preference for this brand.</li>
</ul></li>
<li><p><strong>Beta for Brand 2 (<code>beta_2</code>)</strong>: 0.644</p>
<ul>
<li>Similarly, this positive intercept indicates a preference for Brand 2 over Brand 4, though the preference is less strong compared to Brand 1. Brand 2 is still preferred but not as much as Brand 1.</li>
</ul></li>
<li><p><strong>Beta for Brand 3 (<code>beta_3</code>)</strong>: −3.086</p>
<ul>
<li>The negative value of this intercept indicates that Brand 3 is less preferred compared to Brand 4. This substantial negative value suggests a strong aversion to Brand 3 relative to the other options.</li>
</ul></li>
</ol>
</section>
<section id="which-yogurt-is-most-preferred" class="level3">
<h3 class="anchored" data-anchor-id="which-yogurt-is-most-preferred">Which yogurt is most preferred?</h3>
<p>Based on the magnitude and direction of the beta coefficients:</p>
<ul>
<li><strong>Brand 1</strong> is the most preferred yogurt among the options. It has the highest positive intercept, indicating the strongest preference relative to the baseline (Brand 4).</li>
<li><strong>Brand 2</strong> is also preferred over the baseline but to a lesser extent than Brand 1.</li>
<li><strong>Brand 3</strong> is the least preferred, with a significant negative intercept indicating a strong preference against it compared to Brand 4.</li>
</ul>
<p>This interpretation can help in strategic decisions related to marketing and product placement, such as focusing promotional efforts on Brands 1 and 2, considering price adjustments or rebranding for Brand 3, and understanding the competitive position of Brand 4 as a potentially neutral or fallback option.</p>
<ul>
<li><p><strong>Identify the most and least preferred yogurts</strong>:</p>
<ul>
<li>Most preferred: Brand 1 (intercept = 1.388)</li>
<li>Least preferred: Brand 3 (intercept = -3.086)</li>
</ul></li>
<li><p><strong>Calculate the difference in utilities</strong> between the most preferred and least preferred yogurts:</p></li>
<li><p><strong>Use the price coefficient as a conversion factor</strong>:</p>
<ul>
<li>Price coefficient (<code>beta_p</code>): −37.058</li>
<li>The price coefficient’s magnitude indicates the decrease in the utility of purchasing a yogurt per dollar increase in its price. Therefore, it acts as a conversion factor from utility to dollar value.</li>
</ul></li>
</ul>
<div id="ca99358a" class="cell" data-message="true" data-execution_count="10">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar benefit</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dollar_benefit <span class="op">=</span> utility_difference <span class="op">*</span> dollar_value_per_util</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>dollar_benefit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>-0.12072966700847321</code></pre>
</div>
</div>
<p>The calculated dollar benefit between the most preferred yogurt (Brand 1) and the least preferred yogurt (Brand 3) is approximately -$0.121 per unit. This indicates that consumers might be willing to pay about 12 cents more per unit for Brand 1 over Brand 3 due to their difference in utility, based on the model estimates.</p>
<p>This negative sign might initially seem counterintuitive, but it reflects how much less consumers would be willing to pay for the less preferred option (Brand 3). In other words, Brand 1 has a higher inherent value of about 12 cents per unit over Brand 3 in the eyes of consumers.</p>
<p>This monetary measure effectively quantifies the brand value in dollar terms based on consumer preferences modeled by the MNL. This insight can be leveraged for pricing strategies and marketing efforts to enhance product positioning and profitability.</p>
<p>One benefit of the MNL model is that we can simulate counterfactuals (eg, what if the price of yogurt 1 was $0.10/oz instead of $0.08/oz).</p>
<p>To calculate the market shares and predict the changes in market share due to a price increase for Yogurt 1,</p>
<ul>
<li><p><strong>Calculate Current Market Shares</strong>:</p>
<ul>
<li>Count the number of times each product was chosen and divide by the total number of observations.</li>
</ul></li>
<li><p><strong>Simulate the Effect of a Price Increase for Yogurt 1</strong>:</p>
<ul>
<li>Increase the price of Yogurt 1 by $0.10 and use the fitted model to estimate the choice probabilities for each product and each consumer.</li>
<li>Calculate the expected market shares by taking the average of the choice probabilities across all consumers for each product.</li>
</ul></li>
</ul>
<div id="c3056e52" class="cell" data-message="true" data-execution_count="11">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the current market shares</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>current_market_shares <span class="op">=</span> long_data_final.groupby(<span class="st">'product'</span>)[<span class="st">'choice'</span>].mean()</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Current Market Shares:"</span>, current_market_shares)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Current Market Shares: product
1    0.341975
2    0.401235
3    0.029218
4    0.227572
Name: choice, dtype: float64</code></pre>
</div>
</div>
<div id="d15bf873" class="cell" data-message="true" data-execution_count="13">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Call the function with the original data and fitted beta coefficients</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>new_market_shares <span class="op">=</span> predict_new_market_shares(long_data_final, result.x)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"New Market Shares After Price Increase:"</span>, new_market_shares)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>New Market Shares After Price Increase: product
1    0.021117
2    0.591145
3    0.044040
4    0.343697
Name: probability, dtype: float64</code></pre>
</div>
</div>
<p>Based on the results provided:</p>
</section>
<section id="current-market-shares" class="level3">
<h3 class="anchored" data-anchor-id="current-market-shares">Current Market Shares:</h3>
<ul>
<li><strong>Yogurt 1</strong>: 34.2%</li>
<li><strong>Yogurt 2</strong>: 40.1%</li>
<li><strong>Yogurt 3</strong>: 2.9%</li>
<li><strong>Yogurt 4</strong>: 22.8%</li>
</ul>
</section>
<section id="new-market-shares-after-a-0.10-price-increase-to-yogurt-1" class="level3">
<h3 class="anchored" data-anchor-id="new-market-shares-after-a-0.10-price-increase-to-yogurt-1">New Market Shares After a $0.10 Price Increase to Yogurt 1:</h3>
<ul>
<li><strong>Yogurt 1</strong>: 2.1%</li>
<li><strong>Yogurt 2</strong>: 59.1%</li>
<li><strong>Yogurt 3</strong>: 4.4%</li>
<li><strong>Yogurt 4</strong>: 34.4%</li>
</ul>
</section>
<section id="analysis" class="level3">
<h3 class="anchored" data-anchor-id="analysis">Analysis:</h3>
<ul>
<li><strong>Yogurt 1 Market Share</strong>: The market share for Yogurt 1 drastically decreases from 34.2% to 2.1%. This significant reduction clearly indicates that the price sensitivity for Yogurt 1 is quite high, and even a modest price increase leads to a substantial shift in consumer preferences away from this product.</li>
<li><strong>Shifts to Other Products</strong>: The market shares of Yogurt 2, 3, and 4 all increase. Yogurt 2 benefits the most, with its market share increasing by nearly 19 percentage points. This suggests that consumers consider Yogurt 2 a close substitute for Yogurt 1, switching to it when Yogurt 1 becomes more expensive.</li>
<li><strong>Yogurt 3 and 4</strong>: Even though Yogurt 3 had a very low initial market share, it sees a relative increase, suggesting some consumers might switch to lower preference options if their first choice becomes less economically viable. Yogurt 4 also sees a notable increase in market share.</li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion:</h3>
<p>The $0.10 price increase for Yogurt 1 drastically reduces its market share, confirming the price sensitivity and showing a clear preference shift among consumers to other available options, particularly Yogurt 2. This demonstrates the importance of pricing strategies in competitive markets and highlights the value of using such models for predictive analytics in marketing and pricing decisions.</p>
</section>
</section>
<section id="estimating-minivan-preferences" class="level2">
<h2 class="anchored" data-anchor-id="estimating-minivan-preferences">2. Estimating Minivan Preferences</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div id="3a848c14" class="cell" data-message="true" data-execution_count="14">
<div class="cell-output cell-output-display" data-execution_count="14">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">resp.id</th>
<th data-quarto-table-cell-role="th">ques</th>
<th data-quarto-table-cell-role="th">alt</th>
<th data-quarto-table-cell-role="th">carpool</th>
<th data-quarto-table-cell-role="th">seat</th>
<th data-quarto-table-cell-role="th">cargo</th>
<th data-quarto-table-cell-role="th">eng</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">choice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>35</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>1</td>
<td>2</td>
<td>yes</td>
<td>8</td>
<td>3ft</td>
<td>hyb</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1</td>
<td>1</td>
<td>3</td>
<td>yes</td>
<td>6</td>
<td>3ft</td>
<td>gas</td>
<td>30</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>yes</td>
<td>6</td>
<td>2ft</td>
<td>gas</td>
<td>30</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1</td>
<td>2</td>
<td>2</td>
<td>yes</td>
<td>7</td>
<td>3ft</td>
<td>gas</td>
<td>35</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8995</td>
<td>200</td>
<td>14</td>
<td>2</td>
<td>no</td>
<td>7</td>
<td>3ft</td>
<td>gas</td>
<td>35</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8996</td>
<td>200</td>
<td>14</td>
<td>3</td>
<td>no</td>
<td>7</td>
<td>3ft</td>
<td>hyb</td>
<td>35</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8997</td>
<td>200</td>
<td>15</td>
<td>1</td>
<td>no</td>
<td>7</td>
<td>2ft</td>
<td>gas</td>
<td>35</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">8998</td>
<td>200</td>
<td>15</td>
<td>2</td>
<td>no</td>
<td>8</td>
<td>3ft</td>
<td>elec</td>
<td>40</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8999</td>
<td>200</td>
<td>15</td>
<td>3</td>
<td>no</td>
<td>6</td>
<td>3ft</td>
<td>gas</td>
<td>35</td>
<td>1</td>
</tr>
</tbody>
</table>

<p>9000 rows × 9 columns</p>
</div>
</div>
</div>
</div>
<p>The dataset <code>rintro-chapter13conjoint.csv</code> appears to contain data from a conjoint analysis, typically used to gauge consumer preferences across different product features. Here’s a breakdown of the columns:</p>
<ul>
<li><code>resp.id</code>: Identifier for respondents.</li>
<li><code>ques</code>: Question or scenario number.</li>
<li><code>alt</code>: Alternative options presented within each question.</li>
<li><code>carpool</code>: Indicates if the option includes a carpool feature (yes/no).</li>
<li><code>seat</code>: Number of seats.</li>
<li><code>cargo</code>: Cargo space.</li>
<li><code>eng</code>: Type of engine (e.g., ‘gas’ for gasoline, ‘hyb’ for hybrid).</li>
<li><code>price</code>: Price in thousands of dollars.</li>
<li><code>choice</code>: Binary indicator of whether the respondent chose this alternative (1 for chosen, 0 for not chosen).</li>
</ul>
<div id="89a8e7c5" class="cell" data-message="true" data-execution_count="16">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>num_respondents, tasks_per_respondent.describe(), alternatives_per_task</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>(200,
 count    200.0
 mean      15.0
 std        0.0
 min       15.0
 25%       15.0
 50%       15.0
 75%       15.0
 max       15.0
 Name: ques, dtype: float64,
 3)</code></pre>
</div>
</div>
<p>Here’s a summary of the dataset based on the analysis:</p>
<ol type="1">
<li><p><strong>Number of Respondents</strong>: There are 200 unique respondents who participated in the conjoint survey.</p></li>
<li><p><strong>Choice Tasks Per Respondent</strong>:</p>
<ul>
<li>Each respondent completed 15 choice tasks.</li>
<li>This is consistent across all respondents, as indicated by the lack of variability (standard deviation is 0).</li>
</ul></li>
<li><p><strong>Alternatives Presented in Each Choice Task</strong>:</p>
<ul>
<li>Each choice task presented 3 alternatives to the respondents.</li>
<li>This number is consistent across all tasks and respondents, as shown by the uniform count and lack of variability.</li>
</ul></li>
</ol>
<p>The attributes (levels) were number of seats (6,7,8), cargo space (2ft, 3ft), engine type (gas, hybrid, electric), and price (in thousands of dollars).</p>
</section>
<section id="model" class="level3">
<h3 class="anchored" data-anchor-id="model">Model</h3>
<p>Estimating a MNL model omitting the following levels to avoide multicollinearity (6 seats, 2ft cargo, and gas engine). Include price as a continuous variable. Show a table of coefficients and standard errors. You may use your own likelihood function from above, or you may use a function from a package/library to perform the estimation.</p>
<div id="edc7aba4" class="cell" data-message="true" data-execution_count="18">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a constant to the model (intercept)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there are still any object types</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X.dtypes, y.dtypes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>const        float64
carpool        int64
price          int64
seat_7         int64
seat_8         int64
cargo_3ft      int64
eng_hyb        int64
dtype: object int64</code></pre>
</div>
</div>
<div id="98555fd7" class="cell" data-message="true" data-execution_count="19">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the MNL model</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mnl_model <span class="op">=</span> sm.MNLogit(y, X)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>mnl_result <span class="op">=</span> mnl_model.fit()</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mnl_result.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.591150
         Iterations 5
                          MNLogit Regression Results                          
==============================================================================
Dep. Variable:                 choice   No. Observations:                 9000
Model:                        MNLogit   Df Residuals:                     8993
Method:                           MLE   Df Model:                            6
Date:                Mon, 03 Jun 2024   Pseudo R-squ.:                 0.07127
Time:                        15:43:36   Log-Likelihood:                -5320.3
converged:                       True   LL-Null:                       -5728.6
Covariance Type:            nonrobust   LLR p-value:                4.060e-173
==============================================================================
  choice=1       coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.5121      0.210     21.490      0.000       4.101       4.924
carpool        0.0074      0.051      0.144      0.885      -0.093       0.108
price         -0.1486      0.006    -24.977      0.000      -0.160      -0.137
seat_7        -0.4832      0.058     -8.397      0.000      -0.596      -0.370
seat_8        -0.2645      0.056     -4.687      0.000      -0.375      -0.154
cargo_3ft      0.4099      0.047      8.723      0.000       0.318       0.502
eng_hyb       -0.1102      0.050     -2.203      0.028      -0.208      -0.012
==============================================================================</code></pre>
</div>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<ul>
<li><strong>Price</strong>: The negative coefficient for price (−0.1486) indicates that as the price increases, the likelihood of choosing that option decreases, as expected.</li>
<li><strong>Seat 7 and Seat 8</strong>: Both coefficients are negative, indicating less preference compared to the baseline (6 seats). The magnitude of the coefficient for Seat 7 is larger, suggesting a stronger negative preference compared to Seat 8.</li>
<li><strong>Cargo 3</strong>: The positive coefficient (0.4099) suggests a preference for more cargo space (3ft) over the baseline (2ft).</li>
<li><strong>Eng Hyb</strong>: The slight negative coefficient for the hybrid engine (−0.1102) suggests a slight aversion compared to the gasoline engine, although this effect is relatively small.</li>
</ul>
<p>These coefficients provide insights into the preferences of respondents regarding different features of the products presented in the conjoint study. The standard errors indicate the precision of these estimates, with all p-values being significant, showing strong evidence against the null hypothesis of no effect.</p>
<p>Using the price coefficient as a dollar-per-util conversion factor. What is the dollar value of 3ft of cargo space as compared to 2ft of cargo space?</p>
<div id="b13a3df4" class="cell" data-message="true" data-execution_count="20">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients from the model</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cargo_3ft_coeff <span class="op">=</span> mnl_result.params.loc[<span class="st">'cargo_3ft'</span>][<span class="dv">0</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>price_coeff <span class="op">=</span> mnl_result.params.loc[<span class="st">'price'</span>][<span class="dv">0</span>]</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dollar value of 3ft of cargo space compared to 2ft</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>dollar_value_cargo_3ft <span class="op">=</span> cargo_3ft_coeff <span class="op">/</span> <span class="op">-</span>price_coeff</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>dollar_value_cargo_3ft</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>2.758956397955615</code></pre>
</div>
</div>
<p>The dollar value of having 3ft of cargo space as compared to 2ft, based on the estimated model coefficients, is approximately <strong>$2.76</strong>.</p>
<p>This means that, according to the model, consumers would be willing to pay an additional $2.76 for a vehicle option that offers 3ft of cargo space over one that offers only 2ft, all else being equal. This calculation converts the utility gained from larger cargo space into a monetary equivalent using the sensitivity of consumer choices to changes in price.</p>
<p>Assuming the market consists of the following 6 minivans. Predict the market shares of each minivan in the market.</p>
<table class="table">
<thead>
<tr class="header">
<th>Minivan</th>
<th>Seats</th>
<th>Cargo</th>
<th>Engine</th>
<th>Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>30</td>
</tr>
<tr class="even">
<td>B</td>
<td>6</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="odd">
<td>C</td>
<td>8</td>
<td>2</td>
<td>Gas</td>
<td>30</td>
</tr>
<tr class="even">
<td>D</td>
<td>7</td>
<td>3</td>
<td>Gas</td>
<td>40</td>
</tr>
<tr class="odd">
<td>E</td>
<td>6</td>
<td>2</td>
<td>Elec</td>
<td>40</td>
</tr>
<tr class="even">
<td>F</td>
<td>7</td>
<td>2</td>
<td>Hyb</td>
<td>35</td>
</tr>
</tbody>
</table>
<div id="fe1d6781" class="cell" data-message="true" data-execution_count="22">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate utilities for each minivan</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>utilities <span class="op">=</span> np.dot(X_minivans, mnl_result.params.values)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute market shares using softmax function</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>market_shares <span class="op">=</span> np.exp(utilities) <span class="op">/</span> np.<span class="bu">sum</span>(np.exp(utilities), axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add market shares to the minivans dataframe</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>minivans[<span class="st">'Market Share'</span>] <span class="op">=</span> market_shares</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>minivans[[<span class="st">'Minivan'</span>, <span class="st">'Market Share'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Minivan</th>
<th data-quarto-table-cell-role="th">Market Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>A</td>
<td>0.204170</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B</td>
<td>0.264023</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>C</td>
<td>0.227573</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>D</td>
<td>0.054479</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>E</td>
<td>0.132099</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>F</td>
<td>0.117656</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="market-share-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="market-share-interpretation">Market Share Interpretation</h3>
<ol type="1">
<li><p><strong>Minivan B (26.40%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 6 seats, 2ft cargo, Gas engine, priced at $30.</li>
<li><strong>Interpretation</strong>: This option has the highest market share, which suggests that a lower price combined with the base features (6 seats, Gas engine) is highly attractive to consumers. The absence of additional features seems to be offset by the lower price.</li>
</ul></li>
<li><p><strong>Minivan C (22.76%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 8 seats, 2ft cargo, Gas engine, also priced at $30.</li>
<li><strong>Interpretation</strong>: The second most popular option, indicating a strong preference for more seating capacity at no additional cost in price, suggesting that consumers value additional seating when all other factors are equal.</li>
</ul></li>
<li><p><strong>Minivan A (20.42%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 7 seats, 2ft cargo, Hybrid engine, priced at $30.</li>
<li><strong>Interpretation</strong>: The presence of a Hybrid engine with moderate pricing and seat count shows significant consumer interest in more environmentally friendly options when they are not priced higher than gas models.</li>
</ul></li>
<li><p><strong>Minivan E (13.21%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 6 seats, 2ft cargo, Electric engine, priced at $40.</li>
<li><strong>Interpretation</strong>: Indicates a moderate interest in electric vehicles, though the higher price seems to be a deterrent compared to cheaper gas options.</li>
</ul></li>
<li><p><strong>Minivan F (11.77%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 7 seats, 2ft cargo, Hybrid engine, priced at $35.</li>
<li><strong>Interpretation</strong>: Similar to Minivan A but slightly more expensive, which slightly reduces its attractiveness despite the hybrid engine.</li>
</ul></li>
<li><p><strong>Minivan D (5.45%)</strong>:</p>
<ul>
<li><strong>Attributes</strong>: 7 seats, 3ft cargo, Gas engine, priced at $40.</li>
<li><strong>Interpretation</strong>: Despite offering more cargo space, its higher price significantly lowers its market share. This suggests that price sensitivity may outweigh the benefit of additional cargo space for many consumers.</li>
</ul></li>
</ol>
</section>
<section id="overall-insights" class="level3">
<h3 class="anchored" data-anchor-id="overall-insights">Overall Insights</h3>
<ul>
<li><strong>Price Sensitivity</strong>: Price plays a crucial role in consumer choices, as seen by the higher market shares of the lower-priced models.</li>
<li><strong>Preference for Seat Capacity</strong>: There is a clear preference for higher seating capacity when the price is held constant.</li>
<li><strong>Eco-friendly Options</strong>: Consumers show interest in hybrid and electric vehicles, but their choices are sensitive to price differences.</li>
<li><strong>Cargo Space Value</strong>: Additional cargo space does not seem to drive higher market share, especially when accompanied by a higher price.</li>
</ul>
<p>These insights could be used to strategize product offerings, pricing decisions, and marketing campaigns by highlighting features that align with consumer preferences.</p>
<p><em>hint: this example is taken from the “R 4 Marketing Research” book by Chapman and Feit. I believe the same example is present in the companion book titled “Python 4 Marketing Research”. I encourage you to attempt these questions on your own, but if you get stuck or would like to compare you results to “the answers,” you may consult the Chapman and Feit books.</em></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>